from __future__ import annotations

from datetime import datetime, timedelta, timezone
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import time
from uuid import uuid4

from fastapi.testclient import TestClient
from sqlalchemy.orm import joinedload

from agent_core_platform_api.config import get_settings
from agent_core_platform_api.db import get_session_factory, reset_database_state
from agent_core_platform_api.execution_runtime import RuntimeCleanupRequest, RuntimeCleanupResult, RuntimeProvisionResult
import agent_core_platform_api.execution_runtime as execution_runtime_module
from agent_core_platform_api.models import OrchestrationLane, Organization
from agent_core_platform_api.orcha_state import OrchaStateStore
from agent_core_platform_api.orchestration_runtime import OrchestrationRuntimeService
from orcha_api.main import app

WORKER_PACKAGE_SRC = Path(__file__).resolve().parents[2] / "packages" / "platform-worker" / "src"
if str(WORKER_PACKAGE_SRC) not in sys.path:
    sys.path.insert(0, str(WORKER_PACKAGE_SRC))

from agent_core_platform_worker.live_runner import process_pending_runner_launches


def _configure_env(
    database_url: str,
    *,
    remote_execution_root: Path,
    orchestration_enabled: bool,
    tick_interval_seconds: str = "5",
    live_runner_codex_bin: Path | None = None,
) -> None:
    os.environ["AGENT_CORE_AUTH_DISABLED"] = "1"
    os.environ["AGENT_CORE_DATABASE_URL"] = database_url
    os.environ["AGENT_CORE_CRYPTO_SEED"] = "agent-core-test-seed"
    os.environ["AGENT_CORE_INITIAL_ORG_NAME"] = "Primary"
    os.environ["AGENT_CORE_INITIAL_ORG_SLUG"] = "primary"
    os.environ["AGENT_CORE_REMOTE_EXECUTION_ROOT"] = str(remote_execution_root)
    os.environ["AGENT_CORE_RUNTIME_PROVIDER_NAMESPACE"] = "test-namespace"
    os.environ["AGENT_CORE_ORCHESTRATION_LOOP_ENABLED"] = "1" if orchestration_enabled else "0"
    os.environ["AGENT_CORE_ORCHESTRATION_TICK_INTERVAL_SECONDS"] = tick_interval_seconds
    os.environ["AGENT_CORE_ORCHESTRATION_MAX_CLAIMS_PER_TICK"] = "2"
    if live_runner_codex_bin is not None:
        os.environ["AGENT_CORE_LIVE_RUNNER_CODEX_BIN"] = str(live_runner_codex_bin)
    else:
        os.environ.pop("AGENT_CORE_LIVE_RUNNER_CODEX_BIN", None)
    os.environ["AGENT_CORE_LIVE_RUNNER_CODEX_SANDBOX"] = "workspace-write"
    get_settings.cache_clear()
    reset_database_state()


def _reset_env() -> None:
    for key in (
        "AGENT_CORE_DATABASE_URL",
        "AGENT_CORE_REMOTE_EXECUTION_ROOT",
        "AGENT_CORE_RUNTIME_PROVIDER_NAMESPACE",
        "AGENT_CORE_ORCHESTRATION_LOOP_ENABLED",
        "AGENT_CORE_ORCHESTRATION_TICK_INTERVAL_SECONDS",
        "AGENT_CORE_ORCHESTRATION_MAX_CLAIMS_PER_TICK",
        "AGENT_CORE_LIVE_RUNNER_CODEX_BIN",
        "AGENT_CORE_LIVE_RUNNER_CODEX_SANDBOX",
    ):
        os.environ.pop(key, None)
    get_settings.cache_clear()
    reset_database_state()


def _git(path: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", "-C", str(path), *args],
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout.strip()


def _run(*args: str) -> str:
    result = subprocess.run(list(args), check=True, capture_output=True, text=True)
    return result.stdout.strip()


def _build_remote_repo(root: Path) -> str:
    bare_repo = root / "remote.git"
    source_repo = root / "source"
    _run("git", "init", "--bare", str(bare_repo))
    _run("git", "init", "--initial-branch=dev", str(source_repo))
    _git(source_repo, "config", "user.email", "test@example.com")
    _git(source_repo, "config", "user.name", "Test User")
    (source_repo / "README.md").write_text("# Fixture\n", encoding="utf-8")
    _git(source_repo, "add", "README.md")
    _git(source_repo, "commit", "-m", "Initial commit")
    _git(source_repo, "remote", "add", "origin", bare_repo.as_uri())
    _git(source_repo, "push", "-u", "origin", "dev")
    return bare_repo.as_uri()


def _write_fake_codex_script(tmp_path: Path) -> Path:
    script_path = tmp_path / "fake_codex.py"
    script_path.write_text(
        """#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path
import sys


def _arg_value(flag: str) -> str | None:
    for index, value in enumerate(sys.argv):
        if value == flag and index + 1 < len(sys.argv):
            return sys.argv[index + 1]
    return None


last_message_path = _arg_value("-o") or _arg_value("--output-last-message")
if last_message_path:
    Path(last_message_path).write_text("Fake Codex lane complete.\\n", encoding="utf-8")
workspace_file = Path.cwd() / "lane-note.md"
workspace_file.write_text("generated by fake codex\\n", encoding="utf-8")

for payload in (
    {"type": "thread.started", "thread_id": "thread-fake-88"},
    {"type": "turn.started"},
    {
        "type": "item.started",
        "item": {
            "id": "item-1",
            "type": "command_execution",
            "command": "/bin/zsh -lc 'git status --short'",
            "aggregated_output": "",
            "exit_code": None,
            "status": "in_progress",
        },
    },
    {
        "type": "item.completed",
        "item": {
            "id": "item-1",
            "type": "command_execution",
            "command": "/bin/zsh -lc 'git status --short'",
            "aggregated_output": "?? lane-note.md\\n",
            "exit_code": 0,
            "status": "completed",
        },
    },
    {
        "type": "item.completed",
        "item": {
            "id": "item-2",
            "type": "file_change",
            "changes": [{"path": str(workspace_file), "kind": "add"}],
            "status": "completed",
        },
    },
    {
        "type": "item.completed",
        "item": {
            "id": "item-3",
            "type": "agent_message",
            "text": "Fake Codex lane complete.",
        },
    },
    {
        "type": "turn.completed",
        "usage": {
            "input_tokens": 11,
            "output_tokens": 7,
            "total_tokens": 18,
        },
    },
):
    print(json.dumps(payload), flush=True)
""",
        encoding="utf-8",
    )
    script_path.chmod(0o755)
    return script_path


def _seed_ready_work_item(
    session,
    *,
    clone_url: str,
    issue_number: int,
    governance_posture: str = "operator-gated",
    required_secret_keys: list[str] | None = None,
):
    now = datetime(2026, 3, 17, 12, 0, tzinfo=timezone.utc)
    org = session.query(Organization).filter(Organization.slug == "primary").one()
    store = OrchaStateStore(session)
    product = store.create_product(
        org_id=org.org_id,
        key="orcha",
        name="Orcha",
        status="Active",
        setup_state="ready",
        baseline_channel="stable",
        agent_core_version="0.1.0",
        execution_profile="standard-python",
        effective_config={
            "github": {
                "status_field": "Status",
                "ready_status": "Ready",
                "done_status": "Done",
            },
            "execution": {
                "profile": "standard-python",
                "container_image": "ghcr.io/aegroup/agent-core-runner:stable",
                "workspace_strategy": "branch-per-lane",
                "max_concurrent_lanes": 4,
            },
            "governance": {
                "approval_posture": governance_posture,
                "repo_write_policy": governance_posture,
            },
            "activation": {
                "required_secret_keys": required_secret_keys if required_secret_keys is not None else ["github/app"],
            },
        },
        operator_overrides={},
    )
    repo = store.bind_repository(
        product_id=product.product_id,
        github_repository_node_id="R_kgDOIssue54",
        owner="aegroup-io",
        name="orcha",
        default_branch="dev",
        visibility="private",
        seed_source="agent-core",
        adoption_state="adopted",
        raw_payload={"clone_url": clone_url},
    )
    project = store.create_project_mirror(
        product_id=product.product_id,
        github_project_node_id="PVT_issue54",
        number=54,
        title="Issue 54",
        status_field_name="Status",
        status_options=["Ready", "In Progress", "Done"],
        mirror_version=1,
    )
    product.primary_repo_id = repo.repo_id
    product.primary_project_id = project.project_id
    work_item = store.create_work_item(
        repo_id=repo.repo_id,
        project_id=project.project_id,
        github_issue_node_id="I_kwDOIssue54",
        issue_number=issue_number,
        title="Wire live orchestration runtime",
        body="Exercise the live claim to runner-launch path.",
        status="Ready",
        labels=[],
        assignees=[],
        dependencies=[],
        dependency_state="clear",
        priority_hint=None,
        linked_prs=[],
        eligibility_flags=["eligible"],
        handoff_status="none",
        requires_repair=False,
        created_at=now - timedelta(days=1),
        updated_at=now,
    )
    store.create_project_item_mirror(
        project_id=project.project_id,
        github_project_item_node_id="PVTI_issue54",
        github_content_node_id=work_item.github_issue_node_id,
        content_type="Issue",
        work_item_id=work_item.work_item_id,
        status_name="Ready",
        field_values_payload=[
            {
                "field_name": "Status",
                "value": "Ready",
                "updated_at": now.isoformat(),
            }
        ],
        raw_payload={},
        last_reconciled_at=now,
    )
    session.commit()
    return work_item.work_item_id


def _load_lane():
    with get_session_factory()() as session:
        return (
            session.query(OrchestrationLane)
            .options(
                joinedload(OrchestrationLane.execution_environment),
                joinedload(OrchestrationLane.agent_session),
                joinedload(OrchestrationLane.work_item),
            )
            .one_or_none()
        )


def test_lifespan_orchestration_loop_claims_and_prepares_launches() -> None:
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        remote_root = temp_path / "remote-execution"
        _configure_env(
            f"sqlite+pysqlite:///{temp_path / 'runtime.db'}",
            remote_execution_root=remote_root,
            orchestration_enabled=True,
            tick_interval_seconds="0.2",
        )
        clone_url = _build_remote_repo(temp_path)

        with TestClient(app) as client:
            session = get_session_factory()()
            try:
                _seed_ready_work_item(session, clone_url=clone_url, issue_number=54)
            finally:
                session.close()

            deadline = time.monotonic() + 5
            lane = None
            while time.monotonic() < deadline:
                lane = _load_lane()
                if lane is not None and lane.execution_environment is not None and lane.agent_session is not None:
                    break
                time.sleep(0.1)

            assert lane is not None
            assert lane.state == "Provisioning"
            assert lane.execution_environment is not None
            assert lane.execution_environment.status == "Ready"
            assert lane.agent_session is not None
            assert lane.agent_session.status == "launching"
            assert lane.agent_session.launch_payload["issue_context"]["issue_number"] == 54
            assert lane.agent_session.launch_payload["required_capabilities"] == ["approval-gates", "stream-events"]
            assert lane.agent_session.launch_payload["secret_references"] == ["github/app"]

            response = client.get(f"/v1/lanes/{lane.lane_id}")
            assert response.status_code == 200
            assert response.json()["agent_session"]["status"] == "launching"
        _reset_env()


def test_lifespan_orchestration_loop_with_live_worker_auto_advances_lane() -> None:
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        remote_root = temp_path / "remote-execution"
        fake_codex = _write_fake_codex_script(temp_path)
        _configure_env(
            f"sqlite+pysqlite:///{temp_path / 'runtime.db'}",
            remote_execution_root=remote_root,
            orchestration_enabled=True,
            tick_interval_seconds="0.2",
            live_runner_codex_bin=fake_codex,
        )
        clone_url = _build_remote_repo(temp_path)

        with TestClient(app) as client:
            session = get_session_factory()()
            try:
                _seed_ready_work_item(
                    session,
                    clone_url=clone_url,
                    issue_number=88,
                    governance_posture="high-trust",
                    required_secret_keys=[],
                )
            finally:
                session.close()

            deadline = time.monotonic() + 5
            lane = None
            while time.monotonic() < deadline:
                lane = _load_lane()
                if lane is not None and lane.agent_session is not None and lane.agent_session.status == "launching":
                    break
                time.sleep(0.1)

            assert lane is not None
            assert lane.state == "Provisioning"

            processed = process_pending_runner_launches(client, max_launches=1)
            assert processed == 1

            deadline = time.monotonic() + 3
            while time.monotonic() < deadline:
                lane = _load_lane()
                if lane is not None and lane.agent_session is not None and lane.agent_session.status == "completed":
                    break
                time.sleep(0.1)

            assert lane is not None
            assert lane.state == "HandedOff"
            assert lane.agent_session is not None
            assert lane.agent_session.status == "completed"
            assert lane.agent_session.runner_session_id is not None
            assert lane.agent_session.last_event == "session_completed"
            artifact_path = Path(lane.execution_environment.artifact_uri.removeprefix("file://"))
            assert json.loads((artifact_path / "codex-run-result.json").read_text(encoding="utf-8"))["success"] is True
            workspace_path = Path(lane.execution_environment.workspace_uri.removeprefix("file://"))
            assert (workspace_path / "lane-note.md").read_text(encoding="utf-8") == "generated by fake codex\n"
        _reset_env()


def test_lifespan_shutdown_cancels_active_lanes_and_releases_environments(monkeypatch) -> None:
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        remote_root = temp_path / "remote-execution"
        _configure_env(
            f"sqlite+pysqlite:///{temp_path / 'runtime.db'}",
            remote_execution_root=remote_root,
            orchestration_enabled=False,
        )
        clone_url = _build_remote_repo(temp_path)
        cleanup_requests: list[RuntimeCleanupRequest] = []

        class _FakeRuntimeProvider:
            name = "docker"

            def provision(self, request) -> RuntimeProvisionResult:
                lane_root = remote_root / "lanes" / request.environment_id
                workspace_path = (lane_root / "workspace").resolve()
                artifact_path = (lane_root / "artifacts").resolve()
                log_path = (lane_root / "logs").resolve()
                cache_path = (lane_root / "cache").resolve()
                for path in (artifact_path, log_path, cache_path):
                    path.mkdir(parents=True, exist_ok=True)
                if workspace_path.exists():
                    shutil.rmtree(workspace_path)
                workspace_path.mkdir(parents=True, exist_ok=True)
                return RuntimeProvisionResult(
                    runtime_provider=self.name,
                    container_handle=f"docker://{request.environment_id}",
                    workspace_uri=workspace_path.as_uri(),
                    artifact_uri=artifact_path.as_uri(),
                    log_uri=log_path.as_uri(),
                    cache_uri=cache_path.as_uri(),
                    workspace_path=workspace_path,
                    artifact_path=artifact_path,
                    log_path=log_path,
                    cache_path=cache_path,
                    status="Ready",
                    provider_metadata={"container_removed": False},
                )

            def can_reuse(self, environment) -> bool:
                return True

            def cleanup(self, request: RuntimeCleanupRequest) -> RuntimeCleanupResult:
                cleanup_requests.append(request)
                workspace_path = Path(request.workspace_uri.removeprefix("file://")) if request.workspace_uri else None
                if workspace_path is not None and workspace_path.exists():
                    shutil.rmtree(workspace_path)
                return RuntimeCleanupResult(
                    status="Terminated",
                    terminated_at=datetime.now(timezone.utc),
                    provider_metadata={
                        "container_removed": True,
                        "container_reference": request.container_handle.removeprefix("docker://") if request.container_handle else None,
                    },
                )

        fake_provider = _FakeRuntimeProvider()
        monkeypatch.setattr(execution_runtime_module, "build_runtime_provider", lambda settings=None: fake_provider)

        with TestClient(app):
            session = get_session_factory()()
            try:
                _seed_ready_work_item(session, clone_url=clone_url, issue_number=56)
            finally:
                session.close()

            session = get_session_factory()()
            try:
                summary = OrchestrationRuntimeService(session).run_cycle(max_claims=1)
                session.commit()
                assert summary.claimed == 1
                assert summary.provisioned == 1
            finally:
                session.close()

            lane = _load_lane()
            assert lane is not None
            assert lane.state == "Provisioning"
            assert lane.execution_environment is not None
            assert lane.execution_environment.status == "Ready"
            workspace_path = Path(lane.execution_environment.workspace_uri.removeprefix("file://"))
            assert workspace_path.exists()

        lane = _load_lane()
        assert lane is not None
        assert lane.state == "Cancelled"
        assert lane.finished_at is not None
        assert lane.execution_environment is not None
        assert lane.execution_environment.status == "Terminated"
        assert lane.execution_environment.terminated_at is not None
        assert lane.agent_session is not None
        assert lane.agent_session.status == "failed"
        assert lane.agent_session.last_error_category == "integration"
        assert len(cleanup_requests) == 1
        assert cleanup_requests[0].disposition == "terminate"
        assert cleanup_requests[0].reason == "runtime.api_shutdown"
        assert not workspace_path.exists()
        _reset_env()


def test_runner_api_boundaries_update_lane_state_and_session_events() -> None:
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        remote_root = temp_path / "remote-execution"
        _configure_env(
            f"sqlite+pysqlite:///{temp_path / 'runtime.db'}",
            remote_execution_root=remote_root,
            orchestration_enabled=False,
        )
        clone_url = _build_remote_repo(temp_path)

        with TestClient(app) as client:
            session = get_session_factory()()
            try:
                _seed_ready_work_item(session, clone_url=clone_url, issue_number=55)
                summary = OrchestrationRuntimeService(session).run_cycle(max_claims=1)
                session.commit()
                lane = _load_lane()
                assert lane is not None
                assert summary.claimed == 1
                assert summary.provisioned == 1
                assert summary.launches_prepared == 1
                lane_id = str(lane.lane_id)
                environment_identity = lane.execution_environment.container_handle
            finally:
                session.close()

            launch = client.get("/v1/runner/launches/next")
            assert launch.status_code == 200
            launch_payload = launch.json()
            assert launch_payload["lane_id"] == lane_id
            assert launch_payload["required_capabilities"] == ["approval-gates", "stream-events"]

            handshake = client.post(
                f"/v1/runner/lanes/{lane_id}/handshake",
                json={
                    "runner_session_id": "runner-session-55",
                    "runner_version": "agent-core/0.55.0",
                    "capabilities": ["stream-events", "approval-gates"],
                    "environment_identity": environment_identity,
                    "heartbeat_at": "2026-03-17T12:05:00Z",
                    "thread_id": "thread-55",
                },
            )
            assert handshake.status_code == 200
            handshake_payload = handshake.json()
            assert handshake_payload["state"] == "Running"
            assert handshake_payload["agent_session"]["status"] == "running"
            assert handshake_payload["agent_session"]["runner_session_id"] == "runner-session-55"

            heartbeat = client.post(
                f"/v1/runner/lanes/{lane_id}/heartbeat",
                json={
                    "heartbeat_at": "2026-03-17T12:06:00Z",
                    "turn_id": "turn-55",
                },
            )
            assert heartbeat.status_code == 200
            assert heartbeat.json()["agent_session"]["turn_id"] == "turn-55"
            assert heartbeat.json()["agent_session"]["heartbeat_at"].startswith("2026-03-17T12:06:00")

            approval_event = client.post(
                f"/v1/runner/lanes/{lane_id}/events",
                json={
                    "event_type": "approval_requested",
                    "summary": "Need approval before editing tracked files.",
                    "payload": {"action_type": "repo_write"},
                    "observed_at": "2026-03-17T12:07:00Z",
                },
            )
            assert approval_event.status_code == 200
            approval_payload = approval_event.json()
            assert approval_payload["state"] == "AwaitingApproval"
            assert approval_payload["agent_session"]["status"] == "awaiting_approval"
            assert approval_payload["agent_session"]["wait_reason"] == "Need approval before editing tracked files."
        _reset_env()


def test_runner_handshake_rejects_duplicate_session_claims() -> None:
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        remote_root = temp_path / "remote-execution"
        _configure_env(
            f"sqlite+pysqlite:///{temp_path / 'runtime.db'}",
            remote_execution_root=remote_root,
            orchestration_enabled=False,
        )
        clone_url = _build_remote_repo(temp_path)

        with TestClient(app) as client:
            session = get_session_factory()()
            try:
                _seed_ready_work_item(session, clone_url=clone_url, issue_number=56)
                OrchestrationRuntimeService(session).run_cycle(max_claims=1)
                session.commit()
                lane = _load_lane()
                assert lane is not None
                lane_id = str(lane.lane_id)
                environment_identity = lane.execution_environment.container_handle
            finally:
                session.close()

            first = client.post(
                f"/v1/runner/lanes/{lane_id}/handshake",
                json={
                    "runner_session_id": "runner-session-56",
                    "runner_version": "agent-core/0.56.0",
                    "capabilities": ["stream-events", "approval-gates"],
                    "environment_identity": environment_identity,
                    "heartbeat_at": "2026-03-17T12:05:00Z",
                    "thread_id": "thread-56",
                },
            )
            assert first.status_code == 200

            duplicate = client.post(
                f"/v1/runner/lanes/{lane_id}/handshake",
                json={
                    "runner_session_id": "runner-session-56-replay",
                    "runner_version": "agent-core/0.56.1",
                    "capabilities": ["stream-events", "approval-gates"],
                    "environment_identity": environment_identity,
                    "heartbeat_at": "2026-03-17T12:05:30Z",
                    "thread_id": "thread-56b",
                },
            )
            assert duplicate.status_code == 422
            assert "already completed" in duplicate.json()["detail"]

            with get_session_factory()() as verify_session:
                persisted_lane = (
                    verify_session.query(OrchestrationLane)
                    .options(
                        joinedload(OrchestrationLane.execution_environment),
                        joinedload(OrchestrationLane.agent_session),
                    )
                    .one()
                )
                assert persisted_lane.agent_session.runner_session_id == "runner-session-56"
                assert persisted_lane.agent_session.runner_version == "agent-core/0.56.0"
                assert persisted_lane.agent_session.thread_id == "thread-56"
                assert persisted_lane.agent_session.status == "running"
                assert len(persisted_lane.agent_session.events) == 1
        _reset_env()


def test_runner_handshake_rejects_mismatched_environment_identity() -> None:
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        remote_root = temp_path / "remote-execution"
        _configure_env(
            f"sqlite+pysqlite:///{temp_path / 'runtime.db'}",
            remote_execution_root=remote_root,
            orchestration_enabled=False,
        )
        clone_url = _build_remote_repo(temp_path)

        with TestClient(app) as client:
            session = get_session_factory()()
            try:
                _seed_ready_work_item(session, clone_url=clone_url, issue_number=57)
                OrchestrationRuntimeService(session).run_cycle(max_claims=1)
                session.commit()
                lane = _load_lane()
                assert lane is not None
                lane_id = str(lane.lane_id)
            finally:
                session.close()

            handshake = client.post(
                f"/v1/runner/lanes/{lane_id}/handshake",
                json={
                    "runner_session_id": "runner-session-57",
                    "runner_version": "agent-core/0.57.0",
                    "capabilities": ["stream-events", "approval-gates"],
                    "environment_identity": "docker://wrong-container",
                    "heartbeat_at": "2026-03-17T12:05:00Z",
                    "thread_id": "thread-57",
                },
            )
            assert handshake.status_code == 422
            assert "does not match" in handshake.json()["detail"]

            with get_session_factory()() as verify_session:
                persisted_lane = (
                    verify_session.query(OrchestrationLane)
                    .options(
                        joinedload(OrchestrationLane.execution_environment),
                        joinedload(OrchestrationLane.agent_session),
                    )
                    .one()
                )
                assert persisted_lane.agent_session.runner_session_id is None
                assert persisted_lane.agent_session.environment_identity is None
                assert persisted_lane.agent_session.status == "launching"
                assert len(persisted_lane.agent_session.events) == 0
        _reset_env()


def test_runner_api_returns_empty_launch_queue_when_nothing_is_prepared() -> None:
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        remote_root = temp_path / "remote-execution"
        _configure_env(
            f"sqlite+pysqlite:///{temp_path / 'runtime.db'}",
            remote_execution_root=remote_root,
            orchestration_enabled=False,
        )

        with TestClient(app) as client:
            response = client.get("/v1/runner/launches/next")
            assert response.status_code == 204
            assert response.content == b""
        _reset_env()


def test_runner_api_returns_404_for_unknown_lane_ids() -> None:
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        remote_root = temp_path / "remote-execution"
        _configure_env(
            f"sqlite+pysqlite:///{temp_path / 'runtime.db'}",
            remote_execution_root=remote_root,
            orchestration_enabled=False,
        )
        missing_lane_id = uuid4()

        with TestClient(app) as client:
            handshake = client.post(
                f"/v1/runner/lanes/{missing_lane_id}/handshake",
                json={
                    "runner_session_id": "missing-lane-runner",
                    "runner_version": "agent-core/0.60.0",
                    "capabilities": ["stream-events"],
                    "environment_identity": "docker://missing",
                },
            )
            assert handshake.status_code == 404
            assert "Lane not found" in handshake.json()["detail"]

            heartbeat = client.post(
                f"/v1/runner/lanes/{missing_lane_id}/heartbeat",
                json={"turn_id": "turn-missing"},
            )
            assert heartbeat.status_code == 404
            assert "Lane not found" in heartbeat.json()["detail"]

            event = client.post(
                f"/v1/runner/lanes/{missing_lane_id}/events",
                json={"event_type": "status_summary"},
            )
            assert event.status_code == 404
            assert "Lane not found" in event.json()["detail"]
        _reset_env()


def test_runner_events_cannot_bypass_handshake() -> None:
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        remote_root = temp_path / "remote-execution"
        _configure_env(
            f"sqlite+pysqlite:///{temp_path / 'runtime.db'}",
            remote_execution_root=remote_root,
            orchestration_enabled=False,
        )
        clone_url = _build_remote_repo(temp_path)

        with TestClient(app) as client:
            session = get_session_factory()()
            try:
                _seed_ready_work_item(session, clone_url=clone_url, issue_number=58)
                OrchestrationRuntimeService(session).run_cycle(max_claims=1)
                session.commit()
                lane = _load_lane()
                assert lane is not None
                lane_id = str(lane.lane_id)
            finally:
                session.close()

            response = client.post(
                f"/v1/runner/lanes/{lane_id}/events",
                json={
                    "event_type": "session_started",
                    "summary": "Attempt to skip handshake.",
                    "payload": {"runner_session_id": "runner-session-58"},
                    "observed_at": "2026-03-17T12:05:00Z",
                },
            )
            assert response.status_code == 422
            assert "before handshake completed" in response.json()["detail"]

            with get_session_factory()() as verify_session:
                persisted_lane = (
                    verify_session.query(OrchestrationLane)
                    .options(
                        joinedload(OrchestrationLane.execution_environment),
                        joinedload(OrchestrationLane.agent_session),
                    )
                    .one()
                )
                assert persisted_lane.state == "Provisioning"
                assert persisted_lane.agent_session.status == "launching"
                assert persisted_lane.agent_session.runner_session_id is None
                assert len(persisted_lane.agent_session.events) == 0
        _reset_env()


def test_runner_progress_events_cannot_reopen_completed_lane() -> None:
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        remote_root = temp_path / "remote-execution"
        _configure_env(
            f"sqlite+pysqlite:///{temp_path / 'runtime.db'}",
            remote_execution_root=remote_root,
            orchestration_enabled=False,
        )
        clone_url = _build_remote_repo(temp_path)

        with TestClient(app) as client:
            session = get_session_factory()()
            try:
                _seed_ready_work_item(session, clone_url=clone_url, issue_number=59)
                OrchestrationRuntimeService(session).run_cycle(max_claims=1)
                session.commit()
                lane = _load_lane()
                assert lane is not None
                lane_id = str(lane.lane_id)
                environment_identity = lane.execution_environment.container_handle
            finally:
                session.close()

            handshake = client.post(
                f"/v1/runner/lanes/{lane_id}/handshake",
                json={
                    "runner_session_id": "runner-session-59",
                    "runner_version": "agent-core/0.59.0",
                    "capabilities": ["stream-events", "approval-gates"],
                    "environment_identity": environment_identity,
                    "heartbeat_at": "2026-03-17T12:05:00Z",
                },
            )
            assert handshake.status_code == 200

            completed = client.post(
                f"/v1/runner/lanes/{lane_id}/events",
                json={
                    "event_type": "session_completed",
                    "summary": "Runner finished cleanly.",
                    "observed_at": "2026-03-17T12:06:00Z",
                },
            )
            assert completed.status_code == 200
            assert completed.json()["state"] == "HandedOff"
            assert completed.json()["agent_session"]["status"] == "completed"

            late_progress = client.post(
                f"/v1/runner/lanes/{lane_id}/events",
                json={
                    "event_type": "turn_started",
                    "summary": "Late duplicate progress event.",
                    "turn_id": "turn-late",
                    "observed_at": "2026-03-17T12:06:30Z",
                },
            )
            assert late_progress.status_code == 422
            assert "terminal state" in late_progress.json()["detail"]

            with get_session_factory()() as verify_session:
                persisted_lane = (
                    verify_session.query(OrchestrationLane)
                    .options(
                        joinedload(OrchestrationLane.execution_environment),
                        joinedload(OrchestrationLane.agent_session),
                    )
                    .one()
                )
                assert persisted_lane.state == "HandedOff"
                assert persisted_lane.agent_session.status == "completed"
                assert persisted_lane.agent_session.turn_count == 0
                assert persisted_lane.agent_session.last_event == "session_completed"
        _reset_env()
