from __future__ import annotations

import http.server
import json
import socket
import socketserver
import threading
from pathlib import Path
import subprocess
from uuid import uuid4

import httpx

from agent_core_platform_worker.config import WorkerConfig
from agent_core_platform_worker.devserver import process_pending_jobs
from agent_core_platform_worker.live_runner import process_pending_runner_launches
from agent_core_platform_worker.runtime import format_result, run_job, run_job_file
from agent_core_platform_worker.schemas import RequestedBy, WorkerJob


class _ThreadedTCPServer(socketserver.ThreadingMixIn, socketserver.TCPServer):
    allow_reuse_address = True


class _OkHandler(http.server.BaseHTTPRequestHandler):
    def do_GET(self) -> None:  # noqa: N802
        self.send_response(200)
        self.send_header("Content-Type", "text/plain")
        self.end_headers()
        self.wfile.write(b"ok")

    def log_message(self, format: str, *args) -> None:  # noqa: A003
        return None


def _find_free_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.bind(("127.0.0.1", 0))
        return int(sock.getsockname()[1])


def _write_fake_codex_script(tmp_path: Path, *, exit_code: int = 0) -> Path:
    script_path = tmp_path / "fake_codex.py"
    script_path.write_text(
        f"""#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path
import sys


def _arg_value(flag: str) -> str | None:
    for index, value in enumerate(sys.argv):
        if value == flag and index + 1 < len(sys.argv):
            return sys.argv[index + 1]
    return None


prompt_text = sys.stdin.read()
last_message_path = _arg_value("-o") or _arg_value("--output-last-message")
if last_message_path:
    Path(last_message_path).write_text("Fake Codex lane complete.\\n", encoding="utf-8")
workspace_file = Path.cwd() / "lane-note.md"
workspace_file.write_text("generated by fake codex\\n", encoding="utf-8")

events = [
    {{"type": "thread.started", "thread_id": "thread-fake-123"}},
    {{"type": "turn.started"}},
    {{
        "type": "item.started",
        "item": {{
            "id": "item-1",
            "type": "command_execution",
            "command": "/bin/zsh -lc 'git status --short'",
            "aggregated_output": "",
            "exit_code": None,
            "status": "in_progress",
        }},
    }},
    {{
        "type": "item.completed",
        "item": {{
            "id": "item-1",
            "type": "command_execution",
            "command": "/bin/zsh -lc 'git status --short'",
            "aggregated_output": "?? lane-note.md\\n",
            "exit_code": 0,
            "status": "completed",
        }},
    }},
    {{
        "type": "item.completed",
        "item": {{
            "id": "item-2",
            "type": "file_change",
            "changes": [{{"path": str(workspace_file), "kind": "add"}}],
            "status": "completed",
        }},
    }},
    {{
        "type": "item.completed",
        "item": {{
            "id": "item-3",
            "type": "agent_message",
            "text": "Fake Codex lane complete.",
        }},
    }},
    {{
        "type": "turn.completed",
        "usage": {{
            "input_tokens": 12,
            "output_tokens": 8,
            "total_tokens": 20,
        }},
    }},
]

for payload in events:
    print(json.dumps(payload), flush=True)

sys.exit({exit_code})
""",
        encoding="utf-8",
    )
    script_path.chmod(0o755)
    return script_path


def _live_runner_config(*, codex_bin: str) -> WorkerConfig:
    return WorkerConfig(
        api_base_url="http://worker.test",
        request_timeout_seconds=10.0,
        api_token=None,
        live_runner_enabled=True,
        live_runner_version="agent-core-platform-worker/codex-live",
        live_runner_capabilities=("stream-events",),
        live_runner_max_launches_per_poll=2,
        live_runner_codex_bin=codex_bin,
        live_runner_codex_model=None,
        live_runner_codex_sandbox="workspace-write",
        live_runner_heartbeat_interval_seconds=1.0,
    )


def test_api_probe_job_succeeds() -> None:
    port = _find_free_port()
    server = _ThreadedTCPServer(("127.0.0.1", port), _OkHandler)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    try:
        job = WorkerJob(
            job_id=uuid4(),
            job_type="platform.api_probe",
            idempotency_key="probe-1",
            requested_by=RequestedBy(type="system", id="test"),
            payload={"url": f"http://127.0.0.1:{port}/health"},
        )
        result = run_job(job)
        assert result.status == "succeeded"
        assert result.output is not None
        assert result.output["status_code"] == 200
        assert "ok" in result.output["body_preview"]
    finally:
        server.shutdown()
        server.server_close()
        thread.join(timeout=2)


def test_run_job_file_and_format_result(tmp_path: Path) -> None:
    job_path = tmp_path / "job.json"
    job_path.write_text(
        json.dumps(
            {
                "job_id": str(uuid4()),
                "job_type": "platform.settings_snapshot",
                "idempotency_key": "settings-1",
                "requested_by": {"type": "system", "id": "test"},
                "payload": {
                    "settings": [
                        {"scope_type": "user", "key": "shell.locale"},
                        {"scope_type": "user", "key": "shell.theme"},
                    ]
                },
            }
        ),
        encoding="utf-8",
    )
    result = run_job_file(job_path)
    assert result.status == "succeeded"
    assert result.output == {
        "setting_count": 2,
        "keys": ["shell.locale", "shell.theme"],
        "scopes": ["user"],
    }
    assert '"status": "succeeded"' in format_result(result)


def test_unknown_job_type_fails() -> None:
    job = WorkerJob(
        job_id=uuid4(),
        job_type="platform.unknown",
        idempotency_key="unknown-1",
        requested_by=RequestedBy(type="system", id="test"),
        payload={},
    )
    result = run_job(job)
    assert result.status == "failed"
    assert result.error == "Unknown job type: platform.unknown"


def test_devserver_processes_queued_jobs(tmp_path: Path) -> None:
    job_root = tmp_path / "jobs"
    queued = job_root / "queued"
    queued.mkdir(parents=True, exist_ok=True)
    job_path = queued / "settings.json"
    job_path.write_text(
        json.dumps(
            {
                "job_id": str(uuid4()),
                "job_type": "platform.settings_snapshot",
                "idempotency_key": "devserver-1",
                "requested_by": {"type": "service", "id": "test"},
                "payload": {
                    "settings": [
                        {"scope_type": "user", "key": "shell.locale"},
                    ]
                },
            }
        ),
        encoding="utf-8",
    )

    results = process_pending_jobs(job_root)
    assert len(results) == 1
    assert results[0].parent.name == "completed"
    assert not job_path.exists()
    result_payload = json.loads(results[0].read_text(encoding="utf-8"))
    assert result_payload["status"] == "succeeded"


def test_live_runner_processes_launch_with_real_codex_events(tmp_path: Path) -> None:
    requests: list[tuple[str, str, dict]] = []
    workspace_path = tmp_path / "workspace"
    artifact_path = tmp_path / "artifacts"
    log_path = tmp_path / "logs"
    cache_path = tmp_path / "cache"
    workspace_path.mkdir()
    artifact_path.mkdir()
    log_path.mkdir()
    cache_path.mkdir()
    subprocess.run(["git", "-C", str(workspace_path), "init"], check=True, capture_output=True, text=True)

    fake_codex = _write_fake_codex_script(tmp_path)
    launch_payload = {
        "lane_id": "lane-88",
        "agent_session_id": "session-88",
        "lane_metadata": {"environment_identity": "docker://lane-88", "branch_name": "orcha/issue-88-attempt-1"},
        "issue_context": {"issue_number": 88, "title": "Wire live Codex runner"},
        "instruction_bundle": {
            "system_prompt": "Stay within repo policy.",
            "task": "Add the requested lane note.",
            "issue_body": "Create one note file as proof of execution.",
        },
        "policy": {"approval_posture": "high-trust"},
        "artifact_destinations": {
            "workspace_uri": workspace_path.as_uri(),
            "artifact_uri": artifact_path.as_uri(),
            "log_uri": log_path.as_uri(),
            "cache_uri": cache_path.as_uri(),
        },
        "secret_references": [],
        "tool_permissions": ["git.read", "shell.exec"],
        "required_capabilities": ["stream-events"],
    }
    launches = [launch_payload]

    def handler(request: httpx.Request) -> httpx.Response:
        if request.method == "GET" and request.url.path == "/v1/runner/launches/next":
            if launches:
                return httpx.Response(status_code=200, json=launches.pop(0))
            return httpx.Response(status_code=204)
        if request.method == "POST":
            payload = json.loads(request.content.decode("utf-8"))
            requests.append((request.method, request.url.path, payload))
            return httpx.Response(status_code=200, json={"ok": True})
        return httpx.Response(status_code=404, json={"detail": "not found"})

    transport = httpx.MockTransport(handler)
    with httpx.Client(transport=transport, base_url="http://worker.test") as client:
        processed = process_pending_runner_launches(client, max_launches=2, config=_live_runner_config(codex_bin=str(fake_codex)))

    assert processed == 1
    assert requests[0][1] == "/v1/runner/lanes/lane-88/handshake"
    assert requests[0][2]["environment_identity"] == "docker://lane-88"
    event_types = [payload["event_type"] for method, path, payload in requests if path.endswith("/events")]
    assert event_types[:3] == ["status_summary", "status_summary", "turn_started"]
    assert "tool_call_started" in event_types
    assert "tool_call_finished" in event_types
    assert "artifact_created" in event_types
    assert "token_usage_reported" in event_types
    assert "turn_completed" in event_types
    assert event_types[-1] == "session_completed"

    result_payload = json.loads((artifact_path / "codex-run-result.json").read_text(encoding="utf-8"))
    assert result_payload["success"] is True
    assert result_payload["changed_files"] == ["lane-note.md"]
    assert (workspace_path / "lane-note.md").read_text(encoding="utf-8") == "generated by fake codex\n"
    assert (artifact_path / "codex-last-message.md").read_text(encoding="utf-8").strip() == "Fake Codex lane complete."


def test_live_runner_posts_session_failed_when_codex_exits_nonzero(tmp_path: Path) -> None:
    requests: list[tuple[str, str, dict]] = []
    workspace_path = tmp_path / "workspace"
    artifact_path = tmp_path / "artifacts"
    log_path = tmp_path / "logs"
    cache_path = tmp_path / "cache"
    workspace_path.mkdir()
    artifact_path.mkdir()
    log_path.mkdir()
    cache_path.mkdir()
    subprocess.run(["git", "-C", str(workspace_path), "init"], check=True, capture_output=True, text=True)

    fake_codex = _write_fake_codex_script(tmp_path, exit_code=17)
    launch_payload = {
        "lane_id": "lane-89",
        "agent_session_id": "session-89",
        "lane_metadata": {"environment_identity": "docker://lane-89"},
        "issue_context": {"issue_number": 89, "title": "Fail lane"},
        "instruction_bundle": {"system_prompt": "Stay within repo policy.", "task": "Fail the lane.", "issue_body": ""},
        "policy": {"approval_posture": "high-trust"},
        "artifact_destinations": {
            "workspace_uri": workspace_path.as_uri(),
            "artifact_uri": artifact_path.as_uri(),
            "log_uri": log_path.as_uri(),
            "cache_uri": cache_path.as_uri(),
        },
        "secret_references": [],
        "tool_permissions": [],
        "required_capabilities": ["stream-events"],
    }
    launches = [launch_payload]

    def handler(request: httpx.Request) -> httpx.Response:
        if request.method == "GET" and request.url.path == "/v1/runner/launches/next":
            if launches:
                return httpx.Response(status_code=200, json=launches.pop(0))
            return httpx.Response(status_code=204)
        if request.method == "POST":
            payload = json.loads(request.content.decode("utf-8"))
            requests.append((request.method, request.url.path, payload))
            return httpx.Response(status_code=200, json={"ok": True})
        return httpx.Response(status_code=404, json={"detail": "not found"})

    transport = httpx.MockTransport(handler)
    with httpx.Client(transport=transport, base_url="http://worker.test") as client:
        processed = process_pending_runner_launches(client, max_launches=1, config=_live_runner_config(codex_bin=str(fake_codex)))

    assert processed == 1
    event_types = [payload["event_type"] for method, path, payload in requests if path.endswith("/events")]
    assert event_types[-1] == "session_failed"
    result_payload = json.loads((artifact_path / "codex-run-result.json").read_text(encoding="utf-8"))
    assert result_payload["success"] is False
    assert result_payload["exit_code"] == 17
